const ESMessages = {


    "idecontroller": {
        "soundcloud": {
            "description": "EarSketch helps you learn core topics in computer science, music, and music technology in a fun, engaging environment. You learn to code in Python or JavaScript, two of the most popular programming languages in the world, while manipulating loops, composing beats, and applying effects to a multi-track digital audio workstation. To learn more about EarSketch, visit http://earsketch.gatech.edu.",
            "share": "To load this track in EarSketch, visit",
            "code": "This music was generated by the following code:"
        },
        "closealltabs":"This will close all open tabs. Are you sure you want to proceed?",
        "overwrite": "That name already exists. Please provide a unique name or first rename the existing script.",
        "illegalname": "Please use only regular characters, numbers, or _ in file names.",
        "savefailed": "Script could not be saved to the cloud. Please save your script offline to avoid losing changes.",
        "saveallfailed": "Some scripts could not be saved to the cloud. Please save your changes offline to avoid losing them.",
        "blocksyntaxerror": "Failed to switch to the block mode. Please make sure that there is no syntax error in the code."
    },
    "general": {
        "unauthenticated": "Please login before using this feature...",
        "shortname": "Please provide a name that is at least 3 characters long.",
        "loginsuccess": "Login successful",
        "loginfailure": "Your username or password is incorrect. Please try logging in again or register a new account.",
        "soundrenamed": "Successfully renamed sound",
        "renameSoundEmpty": "Sound name cannot be empty (or only contain \"_\")!",
        "renameSoundSpecialChar": "Removing special characters in the renaming process...",
        "renameSoundConflict": "Sound name already in use",
        'illegalCharacterInUserID': 'Please use only regular characters, numbers, or _ in the user ID.',
        'complexitySyntaxError': 'Failed to run the code indicator. There might be a syntax error in your code.',
    },
    "createaccount" : {
        "usernameconstraint": "Usernames must not start with a number and cannot include spaces or special characters",
        "pwdfail": "Your password confirmation is not the same as your password.",
        "pwdlength": "Your password is too short. Passwords must be at least 5 characters long.",
        "timeout": "Timeout communication error.",
        "nopwd": "Please enter password before creating user",
        "usernamelength": "Username length is too long, try with a shorter username",
        "accountsuccess": "User account created succesfully ...",
        "useralreadyexists": "Provided username or email already exists. Please try 'Forgot Password' feature if you cannot access your account.",
        "commerror": "Communication error ...",
        "commerror2": "Communication error ..."
    },
    "shareScript": {
        "menuDescriptions": {
            "viewOnly": "I want someone to see my script. (They cannot edit.)",
            "collaboration": "I want someone to be able to edit my script.",
            "embedded": "I want to be able to embed my song on a website.",
            "soundCloud": "I want to publish my song on SoundCloud."
        },
        "preemptiveSave": 'After putting a user name, you need to press Enter, Tab, Space, or click outside before hitting SAVE. This step checks if the user name exists.'
    }
};

export default ESMessages