export async function getStandardSounds() {
    return [
        {
            artist: "RICHARD DEVINE",
            folder: "DUBSTEP_140_BPM__DUBBASSWOBBLE",
            genre: "DUBSTEP",
            genreGroup: "DUBSTEP",
            instrument: "SYNTH",
            name: "DUBSTEP_BASS_WOBBLE_001",
            path: "filename/placeholder/here.wav",
            public: 1,
            tempo: 140,
            year: 2012,
        },
        {
            artist: "RICHARD DEVINE",
            folder: "DUBSTEP_140_BPM__DUBBASSWOBBLE",
            genre: "DUBSTEP",
            genreGroup: "DUBSTEP",
            instrument: "SYNTH",
            name: "DUBSTEP_BASS_WOBBLE_002",
            path: "filename/placeholder/here.wav",
            public: 1,
            tempo: 140,
            year: 2012,
        },
        {
            artist: "YOUNG GURU",
            folder: "ELECTRO_RHODES",
            genre: "ELECTRO",
            genreGroup: "EDM",
            instrument: "KEYBOARD",
            name: "YG_ELECTRO_RHODES_1",
            path: "filename/placeholder/here.wav",
            public: 1,
            tempo: 90,
            year: 2015,
        },
        {
            artist: "YOUNG GURU",
            folder: "ELECTRO_SNARE",
            genre: "ELECTRO",
            genreGroup: "EDM",
            instrument: "DRUMS",
            name: "YG_ELECTRO_SNARE_1",
            path: "filename/placeholder/here.wav",
            public: 1,
            tempo: 90,
            year: 2015,
        },
    ]
}
