var unit_2_1_1_src = "#\n#\n# script_name: Buzzjam Lite\n#\n# author:\n#\n# description:\n#\n#\n#\n#setup section\nfrom earsketch import *\n\ninit()\nsetTempo(120)\n\n#music section\nsynth1 = TECHNO_SYNTHPLUCK_001\nsynth2 = TECHNO_SYNTHPLUCK_002\ndrums1 = TECHNO_LOOP_PART_002\ndrums2 = TECHNO_LOOP_PART_006\n\n#melody\nfitMedia(synth1, 1, 1, 2)\nfitMedia(synth2, 2, 2, 3)\nfitMedia(synth1, 1, 3, 4)\nfitMedia(synth2, 2, 4, 5)\nfitMedia(synth1, 1, 5, 6)\nfitMedia(synth2, 2, 6, 7)\nfitMedia(synth1, 1, 7, 8)\nfitMedia(synth2, 2, 8, 9)\n#drums\nfitMedia(drums1, 3, 3, 9)\nfitMedia(drums2, 4, 5, 9)\n\n#effects\nsetEffect(3, VOLUME, GAIN, 12.0)\n\n#finish section\nfinish()";
var unit_2_1_1_data = [
    {
        "audioclips": [],
        "effects": []
    },
    {
        "audioclips": [
            {
                "bufferkey": "TECHNO_SYNTHPLUCK_001",
                "belongingtrack": 1,
                "startLocation": 1,
                "mediaStartLocation": 1,
                "mediaEndLocation": 2,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 0,
                "parentId": null,
                "noloop": false
            },
            {
                "bufferkey": "TECHNO_SYNTHPLUCK_001",
                "belongingtrack": 1,
                "startLocation": 3,
                "mediaStartLocation": 1,
                "mediaEndLocation": 2,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 2,
                "parentId": null,
                "noloop": false
            },
            {
                "bufferkey": "TECHNO_SYNTHPLUCK_001",
                "belongingtrack": 1,
                "startLocation": 5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 2,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 4,
                "parentId": null,
                "noloop": false
            },
            {
                "bufferkey": "TECHNO_SYNTHPLUCK_001",
                "belongingtrack": 1,
                "startLocation": 7,
                "mediaStartLocation": 1,
                "mediaEndLocation": 2,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 6,
                "parentId": null,
                "noloop": false
            }
        ],
        "effects": []
    },
    {
        "audioclips": [
            {
                "bufferkey": "TECHNO_SYNTHPLUCK_002",
                "belongingtrack": 2,
                "startLocation": 2,
                "mediaStartLocation": 1,
                "mediaEndLocation": 2,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 1,
                "parentId": null,
                "noloop": false
            },
            {
                "bufferkey": "TECHNO_SYNTHPLUCK_002",
                "belongingtrack": 2,
                "startLocation": 4,
                "mediaStartLocation": 1,
                "mediaEndLocation": 2,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 3,
                "parentId": null,
                "noloop": false
            },
            {
                "bufferkey": "TECHNO_SYNTHPLUCK_002",
                "belongingtrack": 2,
                "startLocation": 6,
                "mediaStartLocation": 1,
                "mediaEndLocation": 2,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 5,
                "parentId": null,
                "noloop": false
            },
            {
                "bufferkey": "TECHNO_SYNTHPLUCK_002",
                "belongingtrack": 2,
                "startLocation": 8,
                "mediaStartLocation": 1,
                "mediaEndLocation": 2,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 7,
                "parentId": null,
                "noloop": false
            }
        ],
        "effects": []
    },
    {
        "audioclips": [
            {
                "bufferkey": "TECHNO_LOOP_PART_002",
                "belongingtrack": 3,
                "startLocation": 3,
                "mediaStartLocation": 1,
                "mediaEndLocation": 3,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 66,
                "parentId": 66
            },
            {
                "bufferkey": "TECHNO_LOOP_PART_002",
                "belongingtrack": 3,
                "startLocation": 5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 3,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 67,
                "parentId": 66
            },
            {
                "bufferkey": "TECHNO_LOOP_PART_002",
                "belongingtrack": 3,
                "startLocation": 7,
                "mediaStartLocation": 1,
                "mediaEndLocation": 3,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 68,
                "parentId": 66
            }
        ],
        "effects": [
            {
                "belongingtrack": 3,
                "effectname": "VOLUME",
                "parameter": "GAIN",
                "effectstartvalue": 3.981071705534973,
                "effectstartvalue_visual": 12,
                "effectstartlocation": 1,
                "effectendvalue": 3.981071705534973,
                "effectendlocation": 0
            }
        ]
    },
    {
        "audioclips": [
            {
                "bufferkey": "TECHNO_LOOP_PART_006",
                "belongingtrack": 4,
                "startLocation": 5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 3,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 69,
                "parentId": 69
            },
            {
                "bufferkey": "TECHNO_LOOP_PART_006",
                "belongingtrack": 4,
                "startLocation": 7,
                "mediaStartLocation": 1,
                "mediaEndLocation": 3,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 70,
                "parentId": 69
            }
        ],
        "effects": []
    },
    {
        "audioclips": [
            {
                "bufferkey": "METRONOME01",
                "belongingtrack": 5,
                "startLocation": 1,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 10,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 1.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 11,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 1.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 12,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 1.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 13,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME01",
                "belongingtrack": 5,
                "startLocation": 2,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 14,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 2.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 15,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 2.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 16,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 2.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 17,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME01",
                "belongingtrack": 5,
                "startLocation": 3,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 18,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 3.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 19,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 3.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 20,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 3.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 21,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME01",
                "belongingtrack": 5,
                "startLocation": 4,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 22,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 4.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 23,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 4.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 24,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 4.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 25,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME01",
                "belongingtrack": 5,
                "startLocation": 5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 26,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 5.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 27,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 5.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 28,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 5.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 29,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME01",
                "belongingtrack": 5,
                "startLocation": 6,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 30,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 6.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 31,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 6.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 32,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 6.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 33,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME01",
                "belongingtrack": 5,
                "startLocation": 7,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 34,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 7.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 35,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 7.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 36,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 7.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 37,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME01",
                "belongingtrack": 5,
                "startLocation": 8,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 38,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 8.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 39,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 8.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 40,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 8.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 41,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 1.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 42,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 1.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 43,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 1.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 44,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 2.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 45,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 2.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 46,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 2.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 47,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 3.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 48,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 3.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 49,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 3.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 50,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 4.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 51,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 4.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 52,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 4.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 53,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 5.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 54,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 5.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 55,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 5.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 56,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 6.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 57,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 6.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 58,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 6.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 59,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 7.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 60,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 7.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 61,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 7.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 62,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 8.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 63,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 8.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 64,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 8.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 65,
                "parentId": null,
                "noloop": true
            }
        ],
        "effects": []
    }
];

var unit_2_2_1_src = "#\n#\n# script_name:\n#\n# author:\n#\n# description:\n#\n#\n#\n#setup section\nfrom earsketch import *\n\ninit()\nsetTempo(120)\n\n#music section\nsynth1 = TECHNO_SYNTHPLUCK_001\nsynth2 = TECHNO_SYNTHPLUCK_002\nintroBeat = TECHNO_LOOP_PART_002\ndrums = TECHNO_LOOP_PART_006\n\n#beats\nintroBeatString1 = \"0-------0-------\"\nmakeBeat(introBeat, 3, 4, introBeatString1)\nmakeBeat(introBeat, 3, 5, introBeatString1)\nmakeBeat(introBeat, 3, 6, introBeatString1)\nmakeBeat(introBeat, 3, 7, introBeatString1)\nmakeBeat(introBeat, 3, 8, introBeatString1)\n\n#melody\nfitMedia(synth1, 1, 1, 2)\nfitMedia(synth2, 2, 2, 3)\nfitMedia(synth1, 1, 3, 4)\nfitMedia(synth2, 2, 4, 5)\nfitMedia(synth1, 1, 5, 6)\nfitMedia(synth2, 2, 6, 7)\nfitMedia(synth1, 1, 7, 8)\nfitMedia(synth2, 2, 8, 9)\n\n#drums\nfitMedia(drums, 4, 5, 9)\n\n#effects\nsetEffect(3, VOLUME, GAIN, 12.0)\n\n#finish section\nfinish()";
var unit_2_2_1_data = [
    {
        "audioclips": [],
        "effects": []
    },
    {
        "audioclips": [
            {
                "bufferkey": "TECHNO_SYNTHPLUCK_001",
                "belongingtrack": 1,
                "startLocation": 1,
                "mediaStartLocation": 1,
                "mediaEndLocation": 2,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 10,
                "parentId": null,
                "noloop": false
            },
            {
                "bufferkey": "TECHNO_SYNTHPLUCK_001",
                "belongingtrack": 1,
                "startLocation": 3,
                "mediaStartLocation": 1,
                "mediaEndLocation": 2,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 12,
                "parentId": null,
                "noloop": false
            },
            {
                "bufferkey": "TECHNO_SYNTHPLUCK_001",
                "belongingtrack": 1,
                "startLocation": 5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 2,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 14,
                "parentId": null,
                "noloop": false
            },
            {
                "bufferkey": "TECHNO_SYNTHPLUCK_001",
                "belongingtrack": 1,
                "startLocation": 7,
                "mediaStartLocation": 1,
                "mediaEndLocation": 2,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 16,
                "parentId": null,
                "noloop": false
            }
        ],
        "effects": []
    },
    {
        "audioclips": [
            {
                "bufferkey": "TECHNO_SYNTHPLUCK_002",
                "belongingtrack": 2,
                "startLocation": 2,
                "mediaStartLocation": 1,
                "mediaEndLocation": 2,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 11,
                "parentId": null,
                "noloop": false
            },
            {
                "bufferkey": "TECHNO_SYNTHPLUCK_002",
                "belongingtrack": 2,
                "startLocation": 4,
                "mediaStartLocation": 1,
                "mediaEndLocation": 2,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 13,
                "parentId": null,
                "noloop": false
            },
            {
                "bufferkey": "TECHNO_SYNTHPLUCK_002",
                "belongingtrack": 2,
                "startLocation": 6,
                "mediaStartLocation": 1,
                "mediaEndLocation": 2,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 15,
                "parentId": null,
                "noloop": false
            },
            {
                "bufferkey": "TECHNO_SYNTHPLUCK_002",
                "belongingtrack": 2,
                "startLocation": 8,
                "mediaStartLocation": 1,
                "mediaEndLocation": 2,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 17,
                "parentId": null,
                "noloop": false
            }
        ],
        "effects": []
    },
    {
        "audioclips": [
            {
                "bufferkey": "TECHNO_LOOP_PART_002",
                "belongingtrack": 3,
                "startLocation": 4,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 0,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "TECHNO_LOOP_PART_002",
                "belongingtrack": 3,
                "startLocation": 4.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 1,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "TECHNO_LOOP_PART_002",
                "belongingtrack": 3,
                "startLocation": 5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 2,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "TECHNO_LOOP_PART_002",
                "belongingtrack": 3,
                "startLocation": 5.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 3,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "TECHNO_LOOP_PART_002",
                "belongingtrack": 3,
                "startLocation": 6,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 4,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "TECHNO_LOOP_PART_002",
                "belongingtrack": 3,
                "startLocation": 6.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 5,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "TECHNO_LOOP_PART_002",
                "belongingtrack": 3,
                "startLocation": 7,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 6,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "TECHNO_LOOP_PART_002",
                "belongingtrack": 3,
                "startLocation": 7.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 7,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "TECHNO_LOOP_PART_002",
                "belongingtrack": 3,
                "startLocation": 8,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 8,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "TECHNO_LOOP_PART_002",
                "belongingtrack": 3,
                "startLocation": 8.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 9,
                "parentId": null,
                "noloop": true
            }
        ],
        "effects": [
            {
                "belongingtrack": 3,
                "effectname": "VOLUME",
                "parameter": "GAIN",
                "effectstartvalue": 3.981071705534973,
                "effectstartvalue_visual": 12,
                "effectstartlocation": 1,
                "effectendvalue": 3.981071705534973,
                "effectendlocation": 0
            }
        ]
    },
    {
        "audioclips": [
            {
                "bufferkey": "TECHNO_LOOP_PART_006",
                "belongingtrack": 4,
                "startLocation": 5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 3,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 75,
                "parentId": 75
            },
            {
                "bufferkey": "TECHNO_LOOP_PART_006",
                "belongingtrack": 4,
                "startLocation": 7,
                "mediaStartLocation": 1,
                "mediaEndLocation": 3,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 76,
                "parentId": 75
            }
        ],
        "effects": []
    },
    {
        "audioclips": [
            {
                "bufferkey": "METRONOME01",
                "belongingtrack": 5,
                "startLocation": 1,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 19,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 1.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 20,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 1.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 21,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 1.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 22,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME01",
                "belongingtrack": 5,
                "startLocation": 2,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 23,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 2.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 24,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 2.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 25,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 2.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 26,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME01",
                "belongingtrack": 5,
                "startLocation": 3,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 27,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 3.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 28,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 3.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 29,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 3.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 30,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME01",
                "belongingtrack": 5,
                "startLocation": 4,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 31,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 4.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 32,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 4.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 33,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 4.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 34,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME01",
                "belongingtrack": 5,
                "startLocation": 5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 35,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 5.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 36,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 5.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 37,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 5.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 38,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME01",
                "belongingtrack": 5,
                "startLocation": 6,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 39,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 6.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 40,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 6.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 41,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 6.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 42,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME01",
                "belongingtrack": 5,
                "startLocation": 7,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 43,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 7.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 44,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 7.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 45,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 7.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 46,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME01",
                "belongingtrack": 5,
                "startLocation": 8,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 47,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 8.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 48,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 8.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 49,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 8.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 50,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 1.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 51,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 1.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 52,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 1.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 53,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 2.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 54,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 2.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 55,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 2.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 56,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 3.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 57,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 3.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 58,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 3.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 59,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 4.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 60,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 4.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 61,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 4.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 62,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 5.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 63,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 5.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 64,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 5.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 65,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 6.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 66,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 6.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 67,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 6.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 68,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 7.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 69,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 7.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 70,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 7.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 71,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 8.25,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 72,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 8.5,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 73,
                "parentId": null,
                "noloop": true
            },
            {
                "bufferkey": "METRONOME02",
                "belongingtrack": 5,
                "startLocation": 8.75,
                "mediaStartLocation": 1,
                "mediaEndLocation": 1.0625,
                "scale": true,
                "src": null,
                "isStarted": false,
                "id": 74,
                "parentId": null,
                "noloop": true
            }
        ],
        "effects": []
    }
];
